code_page_bg_color: 0xFFE8F4F4

code_page_layout:
  - type: image
    url: https://raw.githubusercontent.com/wanjawischmeier/coupons/refs/heads/main/db/shops/rewe/assets/top_area.png
    expanded: false
    goBack: true

  - type: image
    url: https://raw.githubusercontent.com/wanjawischmeier/coupons/refs/heads/main/db/shops/rewe/assets/center_area.png
    expanded: true
    goBack: true

  - type: image
    url: https://raw.githubusercontent.com/wanjawischmeier/coupons/refs/heads/main/db/shops/rewe/assets/bottom_area.png
    expanded: false
    goBack: false
