code_page_bg_color: 0xFFE8F4F4
logo_url: https://raw.githubusercontent.com/wanjawischmeier/coupons/refs/heads/main/assets/rewe/top_area.png

code_page_layout:
  - type: image
    url: https://raw.githubusercontent.com/wanjawischmeier/coupons/refs/heads/main/assets/rewe/top_area.png
    expanded: false
    goBack: true

  - type: spacer
    height: 20

  - type: image
    url: https://raw.githubusercontent.com/wanjawischmeier/coupons/refs/heads/main/assets/rewe/bottom_area.png
    expanded: true
    goBack: false
